seed: 0
exp_name: cyclegan_test # cycle_gan_test_fpucbm_acr_d

device:
  cuda_device: cuda
  gpu_num_workers: 4

dataset:
  FPUCBM_train_val_test: False
  FPUCBM_complete: False
  FPUCBM_test_acr: True
  Public_train_val_test: False

data:
  acr: d #a, b, c, d
  cv: 10
  img_dir: ./data/raw
  fold_dir: ./data/processed/folds
  fold_public_dir: ./data/processed/folds_public
  fold_dir_acr: ./data/processed/folds_acr
  img_dim: 256
  model_dir: ./models
  report_dir: ./reports
  batch_size: 1

model:
  model_name: cycle_gan
  pretrained_model: 'cyclegan_tran_lear'


trainer:
  optimizer:
    lr: 0.00001
  CHECKPOINT_GEN_REC: "genrec.pth.tar"
  CHECKPOINT_GEN_LE: "genle.pth.tar"
  CHECKPOINT_CRITIC_REC: "criticrec.pth.tar"
  CHECKPOINT_CRITIC_LE: "criticle.pth.tar"

output:
  save_img_output: False

